# -*- coding: utf-8 -*-
"""Analse_exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9HBMlfgVQrTGaCScGpABl1johWmRMpq
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#Upload de arquivos

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

df.shape

df.dtypes

#Recetia total
df["Valor Venda"].sum()

#Custo total

df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head(1)

#Custo total

round(df["Custo"].sum(), 2)

#LUCRO

df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(1)

round(df["Lucro"].sum(),2)

#Tempo de envio

df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df.head()

df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head()

df["Tempo_envio"].dtypes #verificação de tipo de variável

#média do tempo de envio
df.groupby("Marca")["Tempo_envio"].mean()

"""#**Missing Values**"""

df.isnull().sum() #verificação de dados faltantes

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

pd.options.display.float_format = '{:20,.2f}'.format

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

#resetando o index

lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()

lucro_ano

#total de produtos vendidos

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de produtos vendidos")
plt.xlabel("Total")
plt.ylabel("Produto")

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita")

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum()

#vendas de 2009

df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009

df_2009.head()

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="LUCRO x MÊS")
plt.xlabel("MÊS")
plt.ylabel("LUCRO")

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="LUCRO  X MÊS")
plt.xlabel("MARCA")
plt.ylabel("LUCRO")
plt.xticks(rotation = "horizontal")

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="LUCRO X CLASSE")
plt.xlabel("CLASSE")
plt.ylabel("LUCRO")
plt.xticks(rotation = "horizontal")

df["Tempo_envio"].describe()

#gráfico de BOXPLOT

plt.boxplot(df["Tempo_envio"]);

plt.hist(df["Tempo_envio"]); #histograma

df['Tempo_envio'].min() #tempo de envio minino

df["Tempo_envio"].max() #tempo de envio máximo

#identificando um outlier

df[df["Tempo_envio"] == 20]

